### ISSUE TITLE
File Detail_screen.dart

### ISSUE THREAD

**Issue by yanissoalili** [Faustharus/gallery#1]
Hi Damien,
You have the urlImage in the first class, there is no need to add a stream.
```dart
class _DetailScreenState extends State<DetailScreen> {
  User? user = FirebaseAuth.instance.currentUser;
  UserModel loggedInUser = UserModel();

  @override
  void initState() {
    super.initState();
    FirebaseFirestore.instance.collection("users").doc(user!.uid).get().then((value) => {
          loggedInUser = UserModel.fromMap(value.data()),
          setState(() {}),
        });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("${loggedInUser.firstName} "),
      ),
      body: InkWell(
        onTap: null,
        child: Hero(tag: widget.urlImage!, child: Image.network(widget.urlImage!)),
      ),
    );
  }
}

**Comment by Faustharus** [comment]
Thank you very much ! - I'll be able to resume with the deleting function now

**Comment by Faustharus** [comment]
Hi @yanissoalili ,
About the deleting function, i've encountered one issue regarding it - I was able the create the function and work just fine if i put the id on the image manually but, based i retrieved the id of the picture by generating one on the gallery page, i was unable to figure out how to get it outside of the gallery page -- The circled word on the picture
<img width="1008" alt="Capture d’écran 2022-02-02 à 09 38 36" src="https://user-images.githubusercontent.com/48592115/152120999-5bd07827-9c2f-4ac7-8de4-db0d56cf5af6.png">

**Comment by yanissoalili** [comment]
Hi @Faustharus ,
just add this 
```dart
 Navigator.push(context,
                              MaterialPageRoute(builder: (_) {
                            return DetailScreen(
                              urlImage: url,
                              currentImage: bigPics,
                             // add this line 
                                idImage : snapshot.data!.docs[index].id,

                            );
                          }));
```

**Comment by Faustharus** [comment]
Thank you again, everything will be done as soon as the hot reload is fixed - i'll send an email during the day

**Comment by yanissoalili** [comment]
@Faustharus, ok

**Comment by yanissoalili** [comment]
good luck
